spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/quest-app
    username: root
    password: 8188121
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8090

